document.getElementById("0").style.display ="block";
document.getElementById("1").style.display ="block";
document.getElementById("2").style.display ="block";
document.getElementById("3").style.display ="block";
document.getElementById("4").style.display ="block";
document.getElementById("5").style.display ="block";
document.getElementById("6").style.display ="none";
document.getElementById("7").style.display ="none";
document.getElementById("8").style.display ="none";
document.getElementById("9").style.display ="none";
document.getElementById("10").style.display ="none";
document.getElementById("11").style.display ="none";
document.getElementById("12").style.display ="none";
document.getElementById("13").style.display ="none";
document.getElementById("14").style.display ="none";
document.getElementById("15").style.display ="none";
document.getElementById("16").style.display ="none";
document.getElementById("17").style.display ="none";
document.getElementById("18").style.display ="none";
document.getElementById("19").style.display ="none";
document.getElementById("20").style.display ="none";
document.getElementById("21").style.display ="none";
document.getElementById("22").style.display ="none";
document.getElementById("23").style.display ="none";
document.getElementById("24").style.display ="none";
document.getElementById("25").style.display ="none";
document.getElementById("26").style.display ="none";
document.getElementById("27").style.display ="none";
document.getElementById("28").style.display ="none";
document.getElementById("29").style.display ="none";

$("#page1").click(function(){
	document.getElementById("0").style.display ="block";
	document.getElementById("1").style.display ="block";
	document.getElementById("2").style.display ="block";
	document.getElementById("3").style.display ="block";
	document.getElementById("4").style.display ="block";
	document.getElementById("5").style.display ="block";
	document.getElementById("6").style.display ="none";
	document.getElementById("7").style.display ="none";
	document.getElementById("8").style.display ="none";
	document.getElementById("9").style.display ="none";
	document.getElementById("10").style.display ="none";
	document.getElementById("11").style.display ="none";
	document.getElementById("12").style.display ="none";
	document.getElementById("13").style.display ="none";
	document.getElementById("14").style.display ="none";
	document.getElementById("15").style.display ="none";
document.getElementById("16").style.display ="none";
document.getElementById("17").style.display ="none";
document.getElementById("18").style.display ="none";
document.getElementById("19").style.display ="none";
document.getElementById("20").style.display ="none";
document.getElementById("21").style.display ="none";
document.getElementById("22").style.display ="none";
document.getElementById("23").style.display ="none";
document.getElementById("24").style.display ="none";
document.getElementById("25").style.display ="none";
document.getElementById("26").style.display ="none";
document.getElementById("27").style.display ="none";
document.getElementById("28").style.display ="none";
document.getElementById("29").style.display ="none";
});
$("#page2").click(function(){
	document.getElementById("0").style.display ="none";
	document.getElementById("1").style.display ="none";
	document.getElementById("2").style.display ="none";
	document.getElementById("3").style.display ="none";
	document.getElementById("4").style.display ="none";
	document.getElementById("5").style.display ="none";
	document.getElementById("6").style.display ="block";
	document.getElementById("7").style.display ="block";
	document.getElementById("8").style.display ="block";
	document.getElementById("9").style.display ="block";
	document.getElementById("10").style.display ="block";
	document.getElementById("11").style.display ="block";
	document.getElementById("12").style.display ="none";
	document.getElementById("13").style.display ="none";
	document.getElementById("14").style.display ="none";
	document.getElementById("15").style.display ="none";
document.getElementById("16").style.display ="none";
document.getElementById("17").style.display ="none";
document.getElementById("18").style.display ="none";
document.getElementById("19").style.display ="none";
document.getElementById("20").style.display ="none";
document.getElementById("21").style.display ="none";
document.getElementById("22").style.display ="none";
document.getElementById("23").style.display ="none";
document.getElementById("24").style.display ="none";
document.getElementById("25").style.display ="none";
document.getElementById("26").style.display ="none";
document.getElementById("27").style.display ="none";
document.getElementById("28").style.display ="none";
document.getElementById("29").style.display ="none";
});
$("#page3").click(function(){
	document.getElementById("0").style.display ="none";
	document.getElementById("1").style.display ="none";
	document.getElementById("2").style.display ="none";
	document.getElementById("3").style.display ="none";
	document.getElementById("4").style.display ="none";
	document.getElementById("5").style.display ="none";
	document.getElementById("6").style.display ="none";
	document.getElementById("7").style.display ="none";
	document.getElementById("8").style.display ="none";
	document.getElementById("9").style.display ="none";
	document.getElementById("10").style.display ="none";
	document.getElementById("11").style.display ="none";
	document.getElementById("12").style.display ="block";
	document.getElementById("13").style.display ="block";
	document.getElementById("14").style.display ="block";
	document.getElementById("15").style.display ="block";
document.getElementById("16").style.display ="block";
document.getElementById("17").style.display ="block";
document.getElementById("18").style.display ="none";
document.getElementById("19").style.display ="none";
document.getElementById("20").style.display ="none";
document.getElementById("21").style.display ="none";
document.getElementById("22").style.display ="none";
document.getElementById("23").style.display ="none";
document.getElementById("24").style.display ="none";
document.getElementById("25").style.display ="none";
document.getElementById("26").style.display ="none";
document.getElementById("27").style.display ="none";
document.getElementById("28").style.display ="none";
document.getElementById("29").style.display ="none";
});
$("#page4").click(function(){
	document.getElementById("0").style.display ="none";
	document.getElementById("1").style.display ="none";
	document.getElementById("2").style.display ="none";
	document.getElementById("3").style.display ="none";
	document.getElementById("4").style.display ="none";
	document.getElementById("5").style.display ="none";
	document.getElementById("6").style.display ="none";
	document.getElementById("7").style.display ="none";
	document.getElementById("8").style.display ="none";
	document.getElementById("9").style.display ="none";
	document.getElementById("10").style.display ="none";
	document.getElementById("11").style.display ="none";
	document.getElementById("12").style.display ="none";
	document.getElementById("13").style.display ="none";
	document.getElementById("14").style.display ="none";
	document.getElementById("15").style.display ="none";
document.getElementById("16").style.display ="none";
document.getElementById("17").style.display ="none";
document.getElementById("18").style.display ="block";
document.getElementById("19").style.display ="block";
document.getElementById("20").style.display ="block";
document.getElementById("21").style.display ="block";
document.getElementById("22").style.display ="block";
document.getElementById("23").style.display ="block";
document.getElementById("24").style.display ="none";
document.getElementById("25").style.display ="none";
document.getElementById("26").style.display ="none";
document.getElementById("27").style.display ="none";
document.getElementById("28").style.display ="none";
document.getElementById("29").style.display ="none";
});
$("#page5").click(function(){
	document.getElementById("0").style.display ="none";
	document.getElementById("1").style.display ="none";
	document.getElementById("2").style.display ="none";
	document.getElementById("3").style.display ="none";
	document.getElementById("4").style.display ="none";
	document.getElementById("5").style.display ="none";
	document.getElementById("6").style.display ="none";
	document.getElementById("7").style.display ="none";
	document.getElementById("8").style.display ="none";
	document.getElementById("9").style.display ="none";
	document.getElementById("10").style.display ="none";
	document.getElementById("11").style.display ="none";
	document.getElementById("12").style.display ="none";
	document.getElementById("13").style.display ="none";
	document.getElementById("14").style.display ="none";
	document.getElementById("15").style.display ="none";
document.getElementById("16").style.display ="none";
document.getElementById("17").style.display ="none";
document.getElementById("18").style.display ="none";
document.getElementById("19").style.display ="none";
document.getElementById("20").style.display ="none";
document.getElementById("21").style.display ="none";
document.getElementById("22").style.display ="none";
document.getElementById("23").style.display ="none";
document.getElementById("24").style.display ="block";
document.getElementById("25").style.display ="block";
document.getElementById("26").style.display ="block";
document.getElementById("27").style.display ="block";
document.getElementById("28").style.display ="block";
document.getElementById("29").style.display ="block";
});

$("#page1").on('click',function(){
	$("#page1").css( "background-color", "#007882");
	$("#page2,#page3,#page4,#page5").css( "background-color", "rgba(0,0,0,0)");
});
$("#page2").on('click',function(){
	$("#page2").css( "background-color", "#007882");
	$("#page1,#page3,#page4,#page5").css( "background-color", "rgba(0,0,0,0)");
});
$("#page3").on('click',function(){
	$("#page3").css( "background-color", "#007882");
	$("#page1,#page2,#page4,#page5").css( "background-color", "rgba(0,0,0,0)");
});
$("#page4").on('click',function(){
	$("#page4").css( "background-color", "#007882");
	$("#page1,#page2,#page3,#page5").css( "background-color", "rgba(0,0,0,0)");
});
$("#page5").on('click',function(){
	$("#page5").css( "background-color", "#007882");
	$("#page1,#page2,#page3,#page4").css( "background-color", "rgba(0,0,0,0)");
});
